name: 'Get a Release'
description: 'Get a given release by a tag in your repository'
author: 'PouuleT'
inputs:
  tag_name:
    description: 'The name of the tag that must be retrieved ( defaults to the tag of the current release )'
    required: false
outputs:
  id:
    description: 'The ID of the Release'
  html_url:
    description: 'The URL users can navigate to in order to view the release'
  upload_url:
    description: 'The URL for uploading assets to the release'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'gray-dark'
